sudo: false

language: perl

git:
  depth: 3
  
perl:
  - "5.28"
  - "5.26"

# disable cpanm

before_install: true

install: true

before_script:
  - perlbrew use $PERLVERS
  - ./bootstrap

script:
  - ./configure
  - make
  - make dist
  - mkdir ~/src
  - cp ooceapps*.tar.gz ~/src
  - cd ~/src
  - tar xvf ooceapps*gz
  - cd ooceapps*/
  - ./configure --prefix=$HOME/ooceapps
  - make
  - make install
  - cd $HOME/ooceapps/bin  
  - ./ooceapps version

